name: Continuous Integration

on: [push]

env:
  # "Source" is set in the setup-dotnet action
  VCPKG_BINARY_SOURCES: 'clear;nuget,Source,readwrite'


jobs:
  build:
    strategy:
      matrix:
        os: ['windows-2019', 'ubuntu-20.04', 'macos-latest']
        include:
          - os: 'windows-2019'
            triplet: 'x64-windows'
            dotnet: ''
          - os: 'ubuntu-20.04'
            triplet: 'x64-linux'
            dotnet: 'mono'
          - os: 'macos-latest'
            triplet: 'x64-osx'
            dotnet: 'mono'
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
          # Sets as "Source"
          source-url: https://nuget.pkg.github.com/ekilmer/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'debug nuget config'
        shell: 'bash'
        run: |
          # Written set-dotnet action writes the config here
          cat ../nuget.config

        # Needed for caching the actual vcpkg executable
      - name: 'Restore from cache and install vcpkg'
        uses: lukka/run-vcpkg@v4
        with:
          setupOnly: true

        # Omit this step if using manifests
      - name: 'vcpkg package install deps'
        shell: 'bash'
        run: |
          # Still need to explicitly sest the api key here for whatever reason
          ${{ matrix.dotnet }} $(${VCPKG_ROOT}/vcpkg fetch nuget | tail -n 1) setapikey ${{ secrets.GITHUB_TOKEN }} -source https://nuget.pkg.github.com/ekilmer/index.json
          "${VCPKG_ROOT}/vcpkg" install fmt --triplet ${{ matrix.triplet }} --debug

      - name: 'Test'
        shell: 'bash'
        run: echo "Hello world"
