name: Continuous Integration

on: [push]

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'


jobs:
  build:
    strategy:
      matrix:
        os: ['windows-2019', 'ubuntu-20.04', 'macos-latest']
        include:
          - os: 'windows-2019'
            triplet: 'x64-windows'
            dotnet: 'dotnet'
          - os: 'ubuntu-20.04'
            triplet: 'x64-linux'
            dotnet: 'mono'
          - os: 'macos-latest'
            triplet: 'x64-osx'
            dotnet: 'mono'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/ekilmer/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 'debug'
        shell: 'bash'
        run: |
          cat nuget.config
          cat ../nuget.config

      - name: 'Restore from cache and install vcpkg'
        uses: lukka/run-vcpkg@v4
        with:
          setupOnly: true

      - name: 'Setup NuGet Credentials'
        shell: 'bash'
        # dotnet "$("${VCPKG_ROOT}/vcpkg" fetch nuget | tail -n 1)"
        run: >
          ${{ matrix.dotnet }} "$("${VCPKG_ROOT}/vcpkg" fetch nuget | tail -n 1)"
          sources add
          -Source https://nuget.pkg.github.com/ekilmer/index.json
          -name GitHub
          -username ekilmer
          -password "${{ secrets.GITHUB_TOKEN }}"
          -storepasswordincleartext

          # Omit this step if using manifests
      - name: 'vcpkg package install deps'
        shell: 'bash'
        run: >
          "${VCPKG_ROOT}/vcpkg" install gtest sqlite3 --triplet ${{ matrix.triplet }} --debug

      - name: 'Test'
        shell: 'bash'
        run: echo "Hello world"
