name: Continuous Integration

on: [push]

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'


jobs:
  build:
    strategy:
      matrix:
        os: ['windows-2019', 'ubuntu-20.04', 'macos-latest']
        include:
          - os: 'windows-2019'
            triplet: 'x64-windows'
          - os: 'ubuntu-20.04'
            triplet: 'x64-linux'
          - os: 'macos-latest'
            triplet: 'x64-osx'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: 'Restore from cache and install vcpkg'
        uses: lukka/run-vcpkg@v4
        with:
          setupOnly: true

      - name: 'Setup NuGet Credentials'
        shell: 'bash'
        run: >
          dotnet "$("${VCPKG_ROOT}/vcpkg" fetch nuget | tail -n 1)"
          add source https://nuget.pkg.github.com/ekilmer/index.json
          -n github
          -u ekilmer
          -p "${{ secrets.GITHUB_TOKEN }}"
          --store-password-in-clear-text

          # Omit this step if using manifests
      - name: 'vcpkg package restore'
        shell: 'bash'
        run: >
          "${VCPKG_ROOT}/vcpkg" install sqlite3 cpprestsdk --triplet ${{ matrix.triplet }}

      - name: 'Test'
        shell: 'bash'
        run: echo "Hello world"
